import { Alignment } from '../../types/Alignment';
import { HeroUnitName } from '../../types/UnitType';
import { PlayerProfile, RaceName } from '../../state/player/PlayerProfile';

export const NO_PLAYER: PlayerProfile = {
  id: 'none',
  name: 'none',
  alignment: Alignment.NEUTRAL,
  race: RaceName.HUMAN,
  type: HeroUnitName.FIGHTER,
  undead: false,
  level: 1,
  description: 'None',
  color: 'white'
};

export const PREDEFINED_PLAYERS: PlayerProfile[] = [
  {
    id: 'alaric',
    name: 'Alaric the Bold',
    alignment: Alignment.LAWFUL,
    race: RaceName.HUMAN,
    type: HeroUnitName.FIGHTER,
    undead: false,
    level: 8,
    description:
      'A noble paladin who has sworn to protect the innocent and uphold justice across the realm.',
    color: 'blue',
  },
  {
    id: 'morgana',
    name: 'Morgana Shadowweaver',
    alignment: Alignment.CHAOTIC,
    race: RaceName.HUMAN,
    type: HeroUnitName.NECROMANCER,
    undead: false,
    level: 12,
    description: 'A powerful sorceress who seeks forbidden knowledge and commands dark magic.',
    color: 'purple',
  },
  {
    id: 'thorin',
    name: 'Thorin Ironforge',
    alignment: Alignment.NEUTRAL,
    race: RaceName.DWARF,
    type: HeroUnitName.HAMMER_LORD,
    undead: false,
    level: 10,
    description: 'A dwarven smith-warrior who values craftsmanship and honor above all else.',
    color: 'orange',
  },
  {
    id: 'kaer',
    name: 'Kaer Dravane',
    alignment: Alignment.NEUTRAL,
    race: RaceName.UNDEAD,
    type: HeroUnitName.WARSMITH,
    undead: true,
    level: 28,
    description: 'A tired soul of bone and will, seeking silence at the edge of eterni',
    color: 'burgundy',
  },
  {
    id: 'vex',
    name: 'Vex the Cunning',
    alignment: Alignment.LAWFUL,
    race: RaceName.ELF,
    type: HeroUnitName.RANGER,
    undead: false,
    level: 7,
    description: 'An elven ranger dedicated to protecting the ancient forests and their secrets.',
    color: 'green',
  },
  {
    id: 'grimjaw',
    name: 'Grimjaw the Destroyer',
    alignment: Alignment.CHAOTIC,
    race: RaceName.ORC,
    type: HeroUnitName.OGR,
    undead: false,
    level: 15,
    description: 'A brutal orc warlord who leads through fear and seeks to conquer all lands.',
    color: 'red',
  },
  {
    id: 'serena',
    name: 'Serena Lightbringer',
    alignment: Alignment.LAWFUL,
    race: RaceName.HUMAN,
    type: HeroUnitName.CLERIC,
    undead: false,
    level: 11,
    description: 'A devout cleric who channels divine power to heal allies and smite evil.',
    color: 'yellow',
  },
  {
    id: 'kael',
    name: 'Kael Stormwind',
    alignment: Alignment.NEUTRAL,
    race: RaceName.HUMAN,
    type: HeroUnitName.ENCHANTER,
    undead: false,
    level: 9,
    description:
      'A wandering mage who seeks to master all schools of magic through experimentation.',
    color: 'blue',
  },
  {
    id: 'elara',
    name: 'Elara Starshot',
    alignment: Alignment.CHAOTIC,
    race: RaceName.ELF,
    type: HeroUnitName.RANGER,
    undead: false,
    level: 6,
    description:
      'A sly rogue who uses wit and stealth to achieve goals through any means necessary.',
    color: 'gray',
  },
  {
    id: 'marcus',
    name: 'Marcus the Divine',
    alignment: Alignment.LAWFUL,
    race: RaceName.HUMAN,
    type: HeroUnitName.CLERIC,
    undead: false,
    level: 13,
    description: 'A devoted priest who spreads hope and healing throughout the lands.',
    color: 'yellow',
  },
  {
    id: 'lydia',
    name: 'Lydia Moonwhisper',
    alignment: Alignment.NEUTRAL,
    race: RaceName.HUMAN,
    type: HeroUnitName.CLERIC,
    undead: false,
    level: 9,
    description: 'A compassionate healer who tends to the wounded with divine grace.',
    color: 'purple',
  },
  {
    id: 'selene',
    name: 'Selene Moonwhisper',
    alignment: Alignment.CHAOTIC,
    race: RaceName.HUMAN,
    type: HeroUnitName.ENCHANTER,
    undead: false,
    level: 9,
    description:
      'A manipulator of perception and dreams, weaving illusions that blur truth and deceit.',
    color: 'darkSlateGray',
  },
  {
    id: 'elderoak',
    name: 'Elderoak the Wise',
    alignment: Alignment.NEUTRAL,
    race: RaceName.ELF,
    type: HeroUnitName.DRUID,
    undead: false,
    level: 14,
    description: 'An ancient druid who maintains the balance between civilization and nature.',
    color: 'green',
  },
  {
    id: 'valdris',
    name: 'Valdris Bonecaller',
    alignment: Alignment.CHAOTIC,
    race: RaceName.HUMAN,
    type: HeroUnitName.NECROMANCER,
    undead: true,
    level: 16,
    description: 'A sinister necromancer who commands the undead and delves into forbidden arts.',
    color: 'purple',
  },
  {
    id: 'ignatius',
    name: 'Ignatius Flameforge',
    alignment: Alignment.NEUTRAL,
    race: RaceName.ORC,
    type: HeroUnitName.PYROMANCER,
    undead: false,
    level: 11,
    description: 'A master of fire magic who forges spells as skillfully as weapons.',
    color: 'orange',
  },
  {
    id: 'ember',
    name: 'Ember Fireheart',
    alignment: Alignment.CHAOTIC,
    race: RaceName.ORC,
    type: HeroUnitName.PYROMANCER,
    undead: false,
    level: 10,
    description: 'A fierce sorceress whose burning passion fuels her destructive fire magic.',
    color: 'red',
  },
  {
    id: 'nullwarden',
    name: 'Thane Nullwarden',
    alignment: Alignment.LAWFUL,
    race: RaceName.HUMAN,
    type: HeroUnitName.ZEALOT,
    undead: false,
    level: 28,
    description: 'A zealot of iron faith, sworn to purge magic from Orrivane.',
    color: 'perl-white',
  },
];
